### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by pstolarz** [SensESP/OneWire#5]
Guys, I'd like you to consider rename of the library for mainly 2 reasons:
* If in the future you'd like to add this lib into Arduino repository, it probably wont be possible due to name conflict with the PaulStoffregen lib.
* If I did know nothing about SignalK and SensESP projects, the first impression I'd have seeing SensESP/OneWire name, would be - oh, just another OneWire fork solving some of its many flaws. Maybe something like SensESPOneWire, SensOneWire etc., would be better candidate for the library name. (You may even consider to introduce a name patter common for all SensESP add-ons to help things sorting out)

**Comment by mairas** [comment]
I wouldn't worry about the name too much. The library is only useful for SensESP users, and for SensESP, Arduino IDE is in my opinion out of scope due to its non-existent dependency management.

Given that PlatformIO's preferred dependency declarations now use the `org/repo` pattern, I don't see much problem for using overlapping library names.

Also, it's likely that the primary library discovery method for SensESP is the GitHub Pages documentation, in development at https://github.com/SignalK/SensESP/blob/v2-dev/docs/, and https://github.com/SignalK/SensESP/blob/v2-dev/docs/pages/additional_resources/add-ons.md, in particular. And in that context the library would always be referred to as `SensESP/OneWire`.

Having said all this, I'm not _completely_ opposed to renaming the library e.g. to `SensESP/SensESPOneWire` or `SensESP/SensESP_OneWire`, but it just feels quite redundant to me, with limited benefit. And for consistency, the same renaming would have to be applied to the other library wrappers at `SensESP/` - `MAX31856` and `ve_direct.mppt`, in particular.

What do you think?

**Comment by pstolarz** [comment]
That's fine. If you don't plan to use this lib via Arduino repository, the justification you provided makes sense. It' would be unnecessary to have `SensESPOneWire` if the library is accessed via `SensESP/OneWire`. I'm just a little oversensitive, when see just another `OneWire` library, since most of them are just Paul Stoffregen's original library offsprings. But maybe I'm not much representative person in this area and other people don't have such impression.
